package com.lixb.mysms.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lixb.mysms.entity.DoHistory;
import com.lixb.mysms.entity.Plan;
import com.lixb.mysms.entity.RepeatTaskInfo;
import com.lixb.mysms.entity.Target;
import com.lixb.mysms.entity.Task;
import com.lixb.mysms.entity.TaskComment;
import com.lixb.mysms.entity.User;

import com.lixb.mysms.db.greendao.DoHistoryDao;
import com.lixb.mysms.db.greendao.PlanDao;
import com.lixb.mysms.db.greendao.RepeatTaskInfoDao;
import com.lixb.mysms.db.greendao.TargetDao;
import com.lixb.mysms.db.greendao.TaskDao;
import com.lixb.mysms.db.greendao.TaskCommentDao;
import com.lixb.mysms.db.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doHistoryDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig repeatTaskInfoDaoConfig;
    private final DaoConfig targetDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig taskCommentDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DoHistoryDao doHistoryDao;
    private final PlanDao planDao;
    private final RepeatTaskInfoDao repeatTaskInfoDao;
    private final TargetDao targetDao;
    private final TaskDao taskDao;
    private final TaskCommentDao taskCommentDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doHistoryDaoConfig = daoConfigMap.get(DoHistoryDao.class).clone();
        doHistoryDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        repeatTaskInfoDaoConfig = daoConfigMap.get(RepeatTaskInfoDao.class).clone();
        repeatTaskInfoDaoConfig.initIdentityScope(type);

        targetDaoConfig = daoConfigMap.get(TargetDao.class).clone();
        targetDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        taskCommentDaoConfig = daoConfigMap.get(TaskCommentDao.class).clone();
        taskCommentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        doHistoryDao = new DoHistoryDao(doHistoryDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        repeatTaskInfoDao = new RepeatTaskInfoDao(repeatTaskInfoDaoConfig, this);
        targetDao = new TargetDao(targetDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        taskCommentDao = new TaskCommentDao(taskCommentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(DoHistory.class, doHistoryDao);
        registerDao(Plan.class, planDao);
        registerDao(RepeatTaskInfo.class, repeatTaskInfoDao);
        registerDao(Target.class, targetDao);
        registerDao(Task.class, taskDao);
        registerDao(TaskComment.class, taskCommentDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        doHistoryDaoConfig.clearIdentityScope();
        planDaoConfig.clearIdentityScope();
        repeatTaskInfoDaoConfig.clearIdentityScope();
        targetDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
        taskCommentDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DoHistoryDao getDoHistoryDao() {
        return doHistoryDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public RepeatTaskInfoDao getRepeatTaskInfoDao() {
        return repeatTaskInfoDao;
    }

    public TargetDao getTargetDao() {
        return targetDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TaskCommentDao getTaskCommentDao() {
        return taskCommentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
